### ISSUE TITLE
EPIC: CMS for Collection Pages

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/arce#34]
'- [x] add video embed link
- [ ] add image to home page for new collections
- [x] generate link to collection search page
- [ ] make "View Items in Collection" more pronounced #107 
- [ ] add content about the collection
- [x] admin only feature
- [x] use same header as about us and our collections
- [x] add collection title to appear on home page block
- [ ] info added into this form will generate a new collection page. collection blocks on home page will now direct to the new collection page
- [x] add google arts and culture embed
