### ISSUE TITLE
Google Arts and Culture

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/arce#35]
**This work to be completed as part of the Collection CMS Epic #79 **

## TODO: 
- [x] Add Google Arts and Culture item to wireframe
- [x] Determine best aspect ratio for the embeds  **16:9**

Examples of Google Arts and Culture embeds: https://artsandculture.google.com/project/preserving-egypt

## Client notes:

On my long list with new website features I didn't add a possible feature that will promote our work we did with Google.

So recently our team published this page on Google Arts and Culture. There are several stories that we could potentially embed in archives.arce.org as Google recently launched an add-on that enables developers to do so. The directions for adding stories are as follows:

> https://support.google.com/culturalinstitute/partners/answer/10968067?hl=en
> Embed Stories - Cultural Institute Platform Help
> Add one or more stories into an existing website or blogEmbedding stories is similar to embedding exhibits, with the difference that a few steps are done in the GA&C Story Editor. Here's how
> support.google.com

NEED FROM ARCE:
- [x] ARCE to check "Allow story to be embedded" on Google Arts and Culture (instructions in link above) 
- [x] List of embed URLs (generated when you follow the directions to allow embedding)
- [x] Location on archives.arce.org where to put the stories - on the new collection pages
