### ISSUE TITLE
[EPIC] Move Arce to r2-besties cluster

### ISSUE THREAD

**Issue by aprilrieger** [scientist-softserv/arce#68]
Arce currently has the following resources:

web
worker
solr
postgresql db
PersistentVolumeClaim: production-arce-rails-env-shared

Goal:
Deploy the workload to a more stable cluster (r2-besties)

Things that need to happen for a production deploy to r2-besties first:

- [ ] backup/restore sql db dump
- [ ] backup/restore PersistentVolumeClaim: production-arce-rails-env-shared
- [ ] update deployment files for production deploy to r2-besties cluster
- [ ] update github actions
- [ ] update/add env variables to github actions for the cluster (KUBECONFIG_FILE, etc)
- [ ] deploy to the new cluster
- [ ] run solr index job on the new arce instance in the new cluster
- [ ] point dns to r2-besties loadbalancer
